name: CI/CD Microservices Deploy

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sonarQube:
    uses: ./.github/workflows/sonar_analysis.yml
    secrets: inherit

  k6-test:
    uses: ./.github/workflows/k6-load-test.yml
    secrets: inherit

  local-deploy:
    needs: [sonarQube, k6-test]
    runs-on: self-hosted
    steps:
      # We do not even need checkout here because we will deploy from your live folder!
      - name: Build and Deploy Local Microservices
        run: |
          # Go to the live production directory on the VM
          cd /home/joshualuna/arroyo_seco_stage2
          
          # Pull the latest code that triggered this pipeline
          git pull origin main
          
          # Build the images using the live docker-compose file
          docker compose build
          
          # Restart the containers (since the directory name is arroyo_seco_stage2, 
          # it will correctly target your existing containers!)
          docker compose up -d --remove-orphans
