name: 🚨 EMERGENCY ROLLBACK
on:
  workflow_dispatch: 

env:
  URL_MAP_NAME: arroyo-seco-canary-lb

jobs:
  abort-canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      - name: Force 100% to V1
        run: |
          echo "itsjluna triggered an emergency rollback. Restoring V1 routes..."
          gcloud compute url-maps import ${{ env.URL_MAP_NAME }} \
            --source=.gcp/routing-100-0.yaml \
            --global \
            --quiet