name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Unit Test Job
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22.20.0, 18.x]
        service: [ 'api-gateway', 'auth-service', 'catalog-service', 'order-service','payment-service', 'reservation-service' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './${{ matrix.service }}/package-lock.json' 

    - name: Install dependencies
      working-directory: ./${{ matrix.service }}
      run: npm ci 

    - name: Run Jest tests
      working-directory: ./${{ matrix.service }}
      run: npm test
